### PR TITLE
correct LGTM.co link

### PR DESCRIPTION
**Pull request by shvaikalesh**

### CODE REVIEW

**Comment by firec0der** [comment]
I'm sorry :(

**Comment by firec0der** [comment]
LGTM

**Comment by tilast** [comment]
kool

**Comment by sudodoki** [comment]
🔥

**Comment by sudodoki** [comment]
Updated slides build in 4c7b228. (Sadly, we can't do jekyll plugins if we are using github-pages, so no automatic rebuild for us. Although, we could do what remark does and translate md -> slides in runtime in html page).

**Pull request merged**
