### PR TITLE
update date

### PR DESCRIPTION
**Pull request by spatialhast**

### CODE REVIEW

**Comment by shvaikalesh** [comment]
Awesome. Also it would be nice to add ES2016, uppercase `Ecma` and update dates, seems like [wiki](https://en.wikipedia.org/wiki/ECMAScript) got it right

Thanks for the PR.

**Comment by sudodoki** [comment]
@spatialhast will you have opportunity to address some notes by @shvaikalesh?

**Comment by firec0der** [comment]
awesome 👍

**Comment by sudodoki** [comment]
@shvaikalesh needs your approval :)

**Comment by shvaikalesh** [comment]
LGTM, thanks

**Pull request merged**
