### PR TITLE
Fix the header transition

### LINKED ISSUE #43: Animated headers become unreadable on hover
Headers with the `.roll` class have an animation effect on hover but sometimes text grows way too big so it doesn't fit in the header box. If I am not mistaken the class is provided by `reveal.js` itself but I suppose we should fix the styles locally. The problem persists in several presentations.
Steps to reproduce:
- Visit this [page](http://kottans.org/js-slides/js_async/#/2);
- Move your cursor over the word `PROMISES`.

Here is a [screenshot](http://i.imgur.com/ZeVfllH.png).

### PR DESCRIPTION
**Pull request by nscyclone**
This should fix #43.
Here is the [screencast](https://drive.google.com/open?id=0B_qNMs7-Bn2UZGhZTzFzV3Z1Njg) of testing this locally.

### CODE REVIEW

**Comment by suchov** [comment]
@sudodoki ^

**Comment by sudodoki** [comment]
Will be rewritten next to me someone runs cleaver. As stated in original issue, might need to patch https://github.com/sudodoki/reveal-cleaver-theme/blob/master/style.css and regenerate

**Comment by sudodoki** [comment]
*next to me -> next time

**Comment by nscyclone** [comment]
@sudodoki, sorry, I am not very familiar with `cleaver` and I couldn't find a mention of any build tool here.
So I suppose in order to fix this I should send a PR to the original [theme](https://github.com/sudodoki/reveal-cleaver-theme/) and then rebuild every presentation that uses it with `cleaver`?
If so I could finish it this evening and rebase this branch with the corresponding updates.

**Comment by sudodoki** [comment]
@nscyclone yep, that would be the best possible solution for this. Thanks for your time

**Comment by nscyclone** [comment]
@sudodoki, I've just rebuilt every presentation that uses the mentioned theme using `cleaver` and rebased the branch.

**Comment by sudodoki** [comment]
@nscyclone can you check the colors on code blocks? Given some changes to CSS those might have broken.

**Comment by nscyclone** [comment]
@sudodoki, I couldn't find any serious visual difference in colors between this branch and `gh-pages`. I also suppose that the CSS changes are expected since they appear as a result of evolving of the original theme. 
The only issue I've found is [this](https://github.com/Kottans/js-slides/pull/44/files#diff-5e4427a61c8137bd63be327c6059d4b8L729) line: the inline style for the code block on the `Callback hell` slide was removed after rebuild and now the block height is smaller than the content so both scrolls appear (there is a `max-height: 400px;` rule on `.reveal pre code` for some reason). Actually the lines 15 and 16 did never fit horizontally as you may see [here](http://kottans.org/js-slides/js_async/#/).
So what do you think we should do with all of this?
Maybe that `max-height` rule is not very useful so we could remove it from the theme? And some inline `font-size` or code rearranging might work for the `Callback hell` slide.

**Comment by sudodoki** [comment]
@nscyclone if so, than it's good to go. Issue with these slides is that they are outdated for most parts, as everything is changing in JS landscape. So yeah, this is good if it only breaks in one place. Going to merge it, unless someone else says anything in next few hours.

**Comment by sudodoki** [comment]
Hah, those few hours spanned a long time 😊

**Pull request merged**
